# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FwCfgGenMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(494, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Downloads/flame3.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tablFirewallConfig = QtGui.QTabWidget(self.centralwidget)
        self.tablFirewallConfig.setGeometry(QtCore.QRect(0, 0, 491, 551))
        self.tablFirewallConfig.setElideMode(QtCore.Qt.ElideRight)
        self.tablFirewallConfig.setObjectName(_fromUtf8("tablFirewallConfig"))
        self.tabNcdSettings = QtGui.QWidget()
        self.tabNcdSettings.setObjectName(_fromUtf8("tabNcdSettings"))
        self.leLocalId = QtGui.QLineEdit(self.tabNcdSettings)
        self.leLocalId.setGeometry(QtCore.QRect(130, 10, 110, 20))
        self.leLocalId.setObjectName(_fromUtf8("leLocalId"))
        self.leLocalLinkNetwork = QtGui.QLineEdit(self.tabNcdSettings)
        self.leLocalLinkNetwork.setGeometry(QtCore.QRect(130, 40, 110, 20))
        self.leLocalLinkNetwork.setObjectName(_fromUtf8("leLocalLinkNetwork"))
        self.leLocalMtuSize = QtGui.QLineEdit(self.tabNcdSettings)
        self.leLocalMtuSize.setGeometry(QtCore.QRect(130, 100, 110, 20))
        self.leLocalMtuSize.setObjectName(_fromUtf8("leLocalMtuSize"))
        self.leLocalPsk = QtGui.QLineEdit(self.tabNcdSettings)
        self.leLocalPsk.setGeometry(QtCore.QRect(130, 130, 241, 20))
        self.leLocalPsk.setObjectName(_fromUtf8("leLocalPsk"))
        self.laLocalId = QtGui.QLabel(self.tabNcdSettings)
        self.laLocalId.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.laLocalId.setObjectName(_fromUtf8("laLocalId"))
        self.laLocalLinkNetwork = QtGui.QLabel(self.tabNcdSettings)
        self.laLocalLinkNetwork.setGeometry(QtCore.QRect(20, 40, 111, 16))
        self.laLocalLinkNetwork.setObjectName(_fromUtf8("laLocalLinkNetwork"))
        self.laLocalEncryption = QtGui.QLabel(self.tabNcdSettings)
        self.laLocalEncryption.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.laLocalEncryption.setObjectName(_fromUtf8("laLocalEncryption"))
        self.laLocalMtuSize = QtGui.QLabel(self.tabNcdSettings)
        self.laLocalMtuSize.setGeometry(QtCore.QRect(20, 100, 111, 16))
        self.laLocalMtuSize.setObjectName(_fromUtf8("laLocalMtuSize"))
        self.laLocalPsk = QtGui.QLabel(self.tabNcdSettings)
        self.laLocalPsk.setGeometry(QtCore.QRect(20, 130, 111, 16))
        self.laLocalPsk.setObjectName(_fromUtf8("laLocalPsk"))
        self.cbLocalEncryption = QtGui.QComboBox(self.tabNcdSettings)
        self.cbLocalEncryption.setGeometry(QtCore.QRect(130, 70, 111, 22))
        self.cbLocalEncryption.setObjectName(_fromUtf8("cbLocalEncryption"))
        self.cbLocalEncryption.addItem(_fromUtf8(""))
        self.cbLocalEncryption.addItem(_fromUtf8(""))
        self.cbLocalEncryption.addItem(_fromUtf8(""))
        self.laLocalFwModel = QtGui.QLabel(self.tabNcdSettings)
        self.laLocalFwModel.setGeometry(QtCore.QRect(20, 160, 51, 16))
        self.laLocalFwModel.setObjectName(_fromUtf8("laLocalFwModel"))
        self.cbLocalFwModel = QtGui.QComboBox(self.tabNcdSettings)
        self.cbLocalFwModel.setGeometry(QtCore.QRect(130, 160, 111, 22))
        self.cbLocalFwModel.setObjectName(_fromUtf8("cbLocalFwModel"))
        self.cbLocalFwModel.addItem(_fromUtf8(""))
        self.cbLocalFwModel.addItem(_fromUtf8(""))
        self.tablFirewallConfig.addTab(self.tabNcdSettings, _fromUtf8(""))
        self.tabRemoteSettings = QtGui.QWidget()
        self.tabRemoteSettings.setObjectName(_fromUtf8("tabRemoteSettings"))
        self.laRssId = QtGui.QLabel(self.tabRemoteSettings)
        self.laRssId.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.laRssId.setObjectName(_fromUtf8("laRssId"))
        self.laRssLinkNetwork = QtGui.QLabel(self.tabRemoteSettings)
        self.laRssLinkNetwork.setGeometry(QtCore.QRect(20, 40, 111, 16))
        self.laRssLinkNetwork.setObjectName(_fromUtf8("laRssLinkNetwork"))
        self.leRssId = QtGui.QLineEdit(self.tabRemoteSettings)
        self.leRssId.setGeometry(QtCore.QRect(130, 10, 110, 20))
        self.leRssId.setObjectName(_fromUtf8("leRssId"))
        self.laRssMtuSize = QtGui.QLabel(self.tabRemoteSettings)
        self.laRssMtuSize.setGeometry(QtCore.QRect(20, 100, 111, 16))
        self.laRssMtuSize.setObjectName(_fromUtf8("laRssMtuSize"))
        self.leRssMtuSize = QtGui.QLineEdit(self.tabRemoteSettings)
        self.leRssMtuSize.setGeometry(QtCore.QRect(130, 100, 110, 20))
        self.leRssMtuSize.setObjectName(_fromUtf8("leRssMtuSize"))
        self.laRssEncryption = QtGui.QLabel(self.tabRemoteSettings)
        self.laRssEncryption.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.laRssEncryption.setObjectName(_fromUtf8("laRssEncryption"))
        self.laRssPsk = QtGui.QLabel(self.tabRemoteSettings)
        self.laRssPsk.setGeometry(QtCore.QRect(20, 130, 111, 16))
        self.laRssPsk.setObjectName(_fromUtf8("laRssPsk"))
        self.leRssLinkNetwork = QtGui.QLineEdit(self.tabRemoteSettings)
        self.leRssLinkNetwork.setGeometry(QtCore.QRect(130, 40, 110, 20))
        self.leRssLinkNetwork.setObjectName(_fromUtf8("leRssLinkNetwork"))
        self.cbRssEncryption = QtGui.QComboBox(self.tabRemoteSettings)
        self.cbRssEncryption.setGeometry(QtCore.QRect(130, 70, 111, 22))
        self.cbRssEncryption.setObjectName(_fromUtf8("cbRssEncryption"))
        self.cbRssEncryption.addItem(_fromUtf8(""))
        self.cbRssEncryption.addItem(_fromUtf8(""))
        self.cbRssEncryption.addItem(_fromUtf8(""))
        self.leRssPsk = QtGui.QLineEdit(self.tabRemoteSettings)
        self.leRssPsk.setGeometry(QtCore.QRect(130, 130, 241, 20))
        self.leRssPsk.setObjectName(_fromUtf8("leRssPsk"))
        self.cbRemoteFwModel = QtGui.QComboBox(self.tabRemoteSettings)
        self.cbRemoteFwModel.setGeometry(QtCore.QRect(130, 160, 111, 22))
        self.cbRemoteFwModel.setObjectName(_fromUtf8("cbRemoteFwModel"))
        self.cbRemoteFwModel.addItem(_fromUtf8(""))
        self.cbRemoteFwModel.addItem(_fromUtf8(""))
        self.laRemoteFwModel = QtGui.QLabel(self.tabRemoteSettings)
        self.laRemoteFwModel.setGeometry(QtCore.QRect(20, 160, 51, 16))
        self.laRemoteFwModel.setObjectName(_fromUtf8("laRemoteFwModel"))
        self.pbGenerate = QtGui.QPushButton(self.tabRemoteSettings)
        self.pbGenerate.setGeometry(QtCore.QRect(130, 200, 75, 23))
        self.pbGenerate.setObjectName(_fromUtf8("pbGenerate"))
        self.tablFirewallConfig.addTab(self.tabRemoteSettings, _fromUtf8(""))
        self.tabFirewallConfig = QtGui.QWidget()
        self.tabFirewallConfig.setObjectName(_fromUtf8("tabFirewallConfig"))
        self.tbLocalFirewallConfig = QtGui.QTextBrowser(self.tabFirewallConfig)
        self.tbLocalFirewallConfig.setGeometry(QtCore.QRect(0, 0, 491, 521))
        self.tbLocalFirewallConfig.setObjectName(_fromUtf8("tbLocalFirewallConfig"))
        self.tablFirewallConfig.addTab(self.tabFirewallConfig, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tbRemoteFirewallConfig = QtGui.QTextBrowser(self.tab)
        self.tbRemoteFirewallConfig.setGeometry(QtCore.QRect(0, 0, 491, 521))
        self.tbRemoteFirewallConfig.setObjectName(_fromUtf8("tbRemoteFirewallConfig"))
        self.tablFirewallConfig.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.mbMenuBar = QtGui.QMenuBar(MainWindow)
        self.mbMenuBar.setGeometry(QtCore.QRect(0, 0, 494, 18))
        self.mbMenuBar.setObjectName(_fromUtf8("mbMenuBar"))
        self.mfMenuFile = QtGui.QMenu(self.mbMenuBar)
        self.mfMenuFile.setObjectName(_fromUtf8("mfMenuFile"))
        self.menuEdit = QtGui.QMenu(self.mbMenuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.mbMenuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.mbMenuBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.acActionClose = QtGui.QAction(MainWindow)
        self.acActionClose.setObjectName(_fromUtf8("acActionClose"))
        self.acClearForms = QtGui.QAction(MainWindow)
        self.acClearForms.setObjectName(_fromUtf8("acClearForms"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.mfMenuFile.addAction(self.actionOpen)
        self.mfMenuFile.addSeparator()
        self.mfMenuFile.addAction(self.actionSave)
        self.mfMenuFile.addAction(self.actionSave_as)
        self.mfMenuFile.addSeparator()
        self.mfMenuFile.addAction(self.acActionClose)
        self.menuEdit.addAction(self.acClearForms)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.mbMenuBar.addAction(self.mfMenuFile.menuAction())
        self.mbMenuBar.addAction(self.menuEdit.menuAction())
        self.mbMenuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tablFirewallConfig.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tablFirewallConfig, self.leLocalId)
        MainWindow.setTabOrder(self.leLocalId, self.leLocalLinkNetwork)
        MainWindow.setTabOrder(self.leLocalLinkNetwork, self.cbLocalEncryption)
        MainWindow.setTabOrder(self.cbLocalEncryption, self.leLocalMtuSize)
        MainWindow.setTabOrder(self.leLocalMtuSize, self.leLocalPsk)
        MainWindow.setTabOrder(self.leLocalPsk, self.cbLocalFwModel)
        MainWindow.setTabOrder(self.cbLocalFwModel, self.leRssId)
        MainWindow.setTabOrder(self.leRssId, self.leRssLinkNetwork)
        MainWindow.setTabOrder(self.leRssLinkNetwork, self.cbRssEncryption)
        MainWindow.setTabOrder(self.cbRssEncryption, self.leRssMtuSize)
        MainWindow.setTabOrder(self.leRssMtuSize, self.leRssPsk)
        MainWindow.setTabOrder(self.leRssPsk, self.cbRemoteFwModel)
        MainWindow.setTabOrder(self.cbRemoteFwModel, self.pbGenerate)
        MainWindow.setTabOrder(self.pbGenerate, self.tbLocalFirewallConfig)
        MainWindow.setTabOrder(self.tbLocalFirewallConfig, self.tbRemoteFirewallConfig)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.leLocalId.setPlaceholderText(_translate("MainWindow", "xxx.xxx.xxx.xxx", None))
        self.leLocalLinkNetwork.setPlaceholderText(_translate("MainWindow", "10.10.10.0/24", None))
        self.leLocalMtuSize.setPlaceholderText(_translate("MainWindow", "1500", None))
        self.laLocalId.setText(_translate("MainWindow", "ID (Public IP)", None))
        self.laLocalLinkNetwork.setText(_translate("MainWindow", "Link Network (CIDR)", None))
        self.laLocalEncryption.setText(_translate("MainWindow", "Encryption", None))
        self.laLocalMtuSize.setText(_translate("MainWindow", "MTU Size (Bytes)", None))
        self.laLocalPsk.setText(_translate("MainWindow", "Pre Shared Key", None))
        self.cbLocalEncryption.setItemText(0, _translate("MainWindow", "AES 256", None))
        self.cbLocalEncryption.setItemText(1, _translate("MainWindow", "AES", None))
        self.cbLocalEncryption.setItemText(2, _translate("MainWindow", "3DES", None))
        self.laLocalFwModel.setText(_translate("MainWindow", "FW Model", None))
        self.cbLocalFwModel.setItemText(0, _translate("MainWindow", "CISCO ASA", None))
        self.cbLocalFwModel.setItemText(1, _translate("MainWindow", "Juniper SRX", None))
        self.tablFirewallConfig.setTabText(self.tablFirewallConfig.indexOf(self.tabNcdSettings), _translate("MainWindow", "Local Site Settings", None))
        self.laRssId.setText(_translate("MainWindow", "ID (Public IP)", None))
        self.laRssLinkNetwork.setText(_translate("MainWindow", "Link Network (CIDR)", None))
        self.leRssId.setPlaceholderText(_translate("MainWindow", "xxx.xxx.xxx.xxx", None))
        self.laRssMtuSize.setText(_translate("MainWindow", "MTU Size (Bytes)", None))
        self.leRssMtuSize.setPlaceholderText(_translate("MainWindow", "1500", None))
        self.laRssEncryption.setText(_translate("MainWindow", "Encryption", None))
        self.laRssPsk.setText(_translate("MainWindow", "Pre Shared Key", None))
        self.leRssLinkNetwork.setPlaceholderText(_translate("MainWindow", "10.10.10.0/24", None))
        self.cbRssEncryption.setItemText(0, _translate("MainWindow", "AES 256", None))
        self.cbRssEncryption.setItemText(1, _translate("MainWindow", "AES", None))
        self.cbRssEncryption.setItemText(2, _translate("MainWindow", "3DES", None))
        self.cbRemoteFwModel.setItemText(0, _translate("MainWindow", "CISCO ASA", None))
        self.cbRemoteFwModel.setItemText(1, _translate("MainWindow", "Juniper SRX", None))
        self.laRemoteFwModel.setText(_translate("MainWindow", "FW Model", None))
        self.pbGenerate.setText(_translate("MainWindow", "Generate", None))
        self.tablFirewallConfig.setTabText(self.tablFirewallConfig.indexOf(self.tabRemoteSettings), _translate("MainWindow", "Remote Site Settings", None))
        self.tablFirewallConfig.setTabText(self.tablFirewallConfig.indexOf(self.tabFirewallConfig), _translate("MainWindow", "Firewall Configuration", None))
        self.tablFirewallConfig.setTabText(self.tablFirewallConfig.indexOf(self.tab), _translate("MainWindow", "Remote FW Settings", None))
        self.mfMenuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as...", None))
        self.acActionClose.setText(_translate("MainWindow", "Close", None))
        self.acClearForms.setText(_translate("MainWindow", "Clear Forms", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

